### ISSUE TITLE
standup download_db <node> local db authentication failed

### ISSUE THREAD

**Issue by footnoise** [creative-co/standup#2]
Try to execute standup download_db < node >

psql -c "select \* from pg_database where datname = '<db_name>'" -U postgres -w
psql: FATAL:  Ident authentication failed for user "postgres"
psql -c "create database <db_name>" -U postgres -w
psql: FATAL:  Ident authentication failed for user "postgres"
psql <db_name> -U postgres -w < tmp/db/dump.sql
psql: FATAL:  Ident authentication failed for user "postgres"

**Comment by Flamefork** [comment]
Best way to avoid this is to change your `pg_hba.conf` to trust local users, for example:

```
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
```
